buildFuture = true
languageCode = 'en-us'
title = 'Nelson Community Land Trust'

[params]
description = 'Building community through shared land ownership in Nelson, BC'
heroImage = '/images/hero.jpg'
